version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: composer install
          command: composer install -n --prefer-dist
          working_directory: ./web
      - run:
          name: composer install
          command: composer require laravel/ui:^1.0 --dev
          working_directory: ./web
      - run: 
          name: npm
          command: npm ci
          working_directory: ./web
      - run: 
          name: npm 2
          command: npm run dev
          working_directory: ./web
      - run:
          name: php test
          command: vendor/bin/phpunit
          working_directory: ./web