version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run: ls -la
      - run:
          name: composer
          command: composer install -n --prefer-dist
          working_directory: ./web
      - run: 
          name: npm
          command: npm install
          working_directory: ./web
      - run: 
          name: npm
          command: npm run dev
          working_directory: ./web