version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers

    working_directory: ./web

    steps:
      - checkout
      - run:
          name: composer install
          command: composer install -n --prefer-dist
      - run:
          name: composer install  laravel/ui
          command: composer require laravel/ui:^1.0 --dev
      - run: 
          name: npm install
          command: npm ci
      - run: 
          name: npm run
          command: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit