version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers

    working_directory: ~/web

    steps:
      - checkout
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit
          
