version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers

    # working_directory: ~/repo

    steps:
      - checkout
      # 保存されたキャッシュを復元
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          working_directory: ./web

      - run:
          name: composer install
          command: composer install -n --prefer-dist
          working_directory: ./web

      - run:
          name: composer install
          command: composer require laravel/ui:^1.0 --dev
          working_directory: ./web

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
          working_directory: ./web

      # 保存されたキャッシュを復元
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          working_directory: ./web

      - run: 
          name: npm
          command: npm ci
          working_directory: ./web

      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi 
          working_directory: ./web

      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
          working_directory: ./web

      - run: 
          name: npm 2
          command: npm run dev
          working_directory: ./web

      - run:
          name: php test
          command: vendor/bin/phpunit
          working_directory: ./web