version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers

    working_directory: ~/web

    steps:
      - checkout
      - run:
        name: composer install
        command: composer install -n --prefer-dist
        working_directory: ~/web
      - run: cd web/
      - run: ls -la
          
